// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OLXAlerts.Api.Data;

#nullable disable

namespace OLXAlerts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526125358_AddPriceRange")]
    partial class AddPriceRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OLXAlerts.Api.Entities.AlertLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("ListingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listing_id");

                    b.Property<string>("MessageSid")
                        .HasColumnType("text")
                        .HasColumnName("message_sid");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("sent")
                        .HasColumnName("status");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_number");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("alert_logs", (string)null);
                });

            modelBuilder.Entity("OLXAlerts.Api.Entities.Listing", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("job_id");

                    b.Property<string>("AdId")
                        .HasColumnType("text")
                        .HasColumnName("ad_id");

                    b.Property<string>("CarBodyType")
                        .HasColumnType("text")
                        .HasColumnName("car_body_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsBusiness")
                        .HasColumnType("boolean")
                        .HasColumnName("is_business");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("OlxCreatedAt")
                        .HasColumnType("text")
                        .HasColumnName("olx_created_at");

                    b.Property<string>("PriceDisplay")
                        .HasColumnType("text")
                        .HasColumnName("price_display");

                    b.Property<decimal?>("PriceValue")
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("price_value");

                    b.Property<string>("RawData")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_data");

                    b.Property<DateTime>("ScrapedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scraped_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id", "JobId");

                    b.HasIndex("JobId");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("OLXAlerts.Api.Entities.SearchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("1000001")
                        .HasColumnName("location_code");

                    b.Property<string>("LocationName")
                        .HasColumnType("text")
                        .HasColumnName("location_name");

                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NextRunAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("NotificationChannel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("notification_channel");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_term");

                    b.Property<long?>("TelegramChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_chat_id");

                    b.Property<string>("WhatsAppNumber")
                        .HasColumnType("text")
                        .HasColumnName("whatsapp_number");

                    b.HasKey("Id");

                    b.ToTable("search_jobs", (string)null);
                });

            modelBuilder.Entity("OLXAlerts.Api.Entities.AlertLog", b =>
                {
                    b.HasOne("OLXAlerts.Api.Entities.SearchJob", "Job")
                        .WithMany("AlertLogs")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OLXAlerts.Api.Entities.Listing", b =>
                {
                    b.HasOne("OLXAlerts.Api.Entities.SearchJob", "Job")
                        .WithMany("Listings")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("OLXAlerts.Api.Entities.SearchJob", b =>
                {
                    b.Navigation("AlertLogs");

                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
